const theme = {
    textVariants: {
        body1: {
            "font-family": "Inter",
            "font-size": "24px",
            "font-weight": "500",
            "letter-spacing": "-0.048rem",
        },
        body1_bold: {
            "font-family": "Inter",
            "font-size": "24px",
            "font-weight": "700",
            "letter-spacing": "-0.048rem",
        },
        body2: {
            "font-family": "Inter",
            "font-size": "28px",
            "font-weight": "500",
            "letter-spacing": "-0.042rem",
        },
        body2_bold: {
            "font-family": "Inter",
            "font-size": "28px",
            "font-weight": "700",
            "letter-spacing": "-0.042rem",
        },
        body3: {
            "font-family": "Inter",
            "font-size": "40px",
            "font-weight": "500",
            "letter-spacing": "-0.048rem",
        },
        body3_bold: {
            "font-family": "Inter",
            "font-size": "40px",
            "font-weight": "700",
            "letter-spacing": "-0.048rem",
        },
        body4: {
            "font-family": "Inter",
            "font-size": "48px",
            "font-weight": "500",
            "letter-spacing": "-0.042rem",
        },
        body4_bold: {
            "font-family": "Inter",
            "font-size": "48px",
            "font-weight": "700",
            "letter-spacing": "-0.042rem",
        },
        body5: {
            "font-family": "Inter",
            "font-size": "20px",
            "font-weight": "500",
            "letter-spacing": "-0.042rem",
        },
        body5_bold: {
            "font-family": "Inter",
            "font-size": "20px",
            "font-weight": "700",
            "letter-spacing": "-0.042rem",
        },
        body6: {
            "font-family": "Inter",
            "font-size": "32px",
            "font-weight": "500",
            "letter-spacing": "-0.042rem",
        },
        body6_bold: {
            "font-family": "Inter",
            "font-size": "32px",
            "font-weight": "700",
            "letter-spacing": "-0.042rem",
        },
        body7: {
            "font-family": "Inter",
            "font-size": "36px",
            "font-weight": "500",
            "letter-spacing": "-0.042rem",
        },
        body7_bold: {
            "font-family": "Inter",
            "font-size": "36px",
            "font-weight": "900",
            "letter-spacing": "-0.042rem",
        },
        head1: {
            "font-family": "Inter",
            "font-size": "64px",
            "font-weight": "500",
            "letter-spacing": "-0.042rem",
        },
        head1_bold: {
            "font-family": "Inter",
            "font-size": "64px",
            "font-weight": "900",
            "letter-spacing": "-0.042rem",
        },
        head2: {
            "font-family": "Inter",
            "font-size": "150px",
            "font-weight": "500",
            "letter-spacing": "-0.042rem",
        },
        head2_bold: {
            "font-family": "Inter",
            "font-size": "150px",
            "font-weight": "900",
            "letter-spacing": "-0.042rem",
        },
    },
    palette: {
        primary: {
            100: "#DBECFD",
            200: "#B8D7FB",
            300: "#93BCF4",
            400: "#75A3EA",
            500: "#4A7EDC",
            600: "#3661BD",
            700: "#25479E",
            800: "#17317F",
            900: "#0E2169",
        },
        gray: {
            900: "#222222",
            800: "#424242",
            700: "#616161",
            600: "#757575",
            500: "#9e9e9e",
            400: "#bdbdbd",
            300: "#e0e0e0",
            200: "#eeeeee",
            100: "#f5f5f5",
            50: "#fafafa",
            black: "#000000",
            white: "#ffffff",
        },
        semantic: {
            success: { 500: "#59BA2C" },
            info: { 500: "#47C1FF" },
            warning: { 500: "#FFB200" },
            danger: { 500: "#FF3A3A" },
        },
    },
    spacing: {
        xxs: "0.4rem",
        xs: "0.8rem",
        sm: "1.2rem",
        md: "1.6rem",
        lg: "2.0rem",
        xl: "2.4rem",
        xxl: "3.2rem",
    },
};
export default theme;
